export const cartTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_SELECTED_ITEM: "REMOVE_SELECTED_ITEM",
  CLEAR_CART: "CLEAR_CART",
  MAKE_CART_EMPTY: "MAKE_CART_EMPTY",
};
